### ISSUE TITLE
CI uses Pylint on fetched Python code (P1)

### ISSUE THREAD

**Issue by AmandaStromdahl** [PersonligaPersson/DD2480_Group_27_CI#8]
Pylint is used to perform a static syntax check on the fetched Python program.

**Comment by mellonnen** [comment]
I was digging around in the [Github action templates](https://github.com/PersonligaPersson/DD2480_Group_27_CI/new/master?filename=.github%2Fworkflows%2Fpython-app.yml&workflow_template=python-app) for python, and found that they used `flake8` for linting instead of `pylint` . Do not really know that much about the differences between the two softwares but it might be good to consider both options

**Comment by PersonligaPersson** [comment]
The CI now uses pylint on fetched code. I will close this issue as it was merged into master in #42 .
